services:
  backend:
    build: .
    container_name: tasks-backend
    restart: always
    ports:
      - 3000:3000
    depends_on: 
      - db
    env_file:
      - .env
    
  db:
    image: postgres:17
    container_name: tasks-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - tasksmanager-data:/var/lib/postgres/data

volumes:
  tasksmanager-data: